services:
  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - my-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  api-golang:
    build:
      context: ./api-golang
      dockerfile: ./Dockerfile.multistage
    image: api-golang:1
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DB_URL}

  api-node:
    build:
      context: ./api-node
      dockerfile: ./Dockerfile
    image: api-node:1
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DB_URL}

  client-react:
    build:
      context: ./client-react
      dockerfile: ./Dockerfile
    image: client-react:1
    ports:
      - "80:8080"
    networks:
      - my-network
    depends_on:
      - api-node
      - api-golang
volumes:
  pgdata:
networks:
  my-network:
    driver: bridge
