services:
  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: foobarbaz
    networks:
      - my-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  api-golang:
    image: api-golang:1
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres

  api-node:
    image: api-node:1
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres

  client-react:
    image: client-react:1
    ports:
      - "80:8080"
    networks:
      - my-network
    depends_on:
      - api-node
      - api-golang
volumes:
  pgdata:
networks:
  my-network:
    driver: bridge
